# Generated by Django 5.0.3 on 2024-03-08 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=64, verbose_name='نام فیلم')),
                ('personal_feedback', models.TextField(verbose_name='نقد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت نقد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان آخرین ویرایش')),
                ('is_active', models.BooleanField(default=False, verbose_name='وظعیت تایید')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='نام فیلم')),
                ('text', models.TextField(verbose_name='متن درباره فیلم')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت فیلم')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی فیلم')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
    ]
