# Generated by Django 5.0.3 on 2024-03-15 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("FinalProject", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedback",
            name="movie_name",
        ),
        migrations.AddField(
            model_name="feedback",
            name="movie",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="FinalProject.movie",
                verbose_name="نام فیلم",
            ),
        ),
    ]
